{{- if gt (.Values.replicaCount | int) 0 }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "kafka-connect.fullname" . }}
  namespace: {{ include "kafka-connect.namespace" . }}
  labels:
    {{- include "kafka-connect.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "kafka-connect.selectorLabels" . | nindent 4 }}
{{- end }}