{{- $mainConfig := .Values.connectors.mainConfig | default "" -}}
{{- if not $mainConfig }}
  {{- if .Values.connectors.mainConfigFile }}
    {{- $mainConfig = .Files.Get .Values.connectors.mainConfigFile -}}
  {{- end }}
{{- end }}
{{- if $mainConfig }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kafka-connect.fullname" . }}-connectors
  labels:
    {{- include "kafka-connect.labels" . | nindent 4 }}
data:
  connectors.yaml: |
{{ $mainConfig | indent 4 }}
{{- end }}

{{- $backupConfig := "" -}}
{{- if (hasKey .Values.connectors "backupConfig") }}
  {{- $backupConfig = .Values.connectors.backupConfig | default "" -}}
{{- else if .Values.connectors.backupConfigFile }}
  {{- $backupConfig = .Files.Get .Values.connectors.backupConfigFile -}}
{{- end }}
{{- if $backupConfig }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kafka-connect.fullname" . }}-backup
  labels:
    {{- include "kafka-connect.labels" . | nindent 4 }}
data:
  bkup_config.json: |
{{ $backupConfig | indent 4 }}
{{- end }}
