# Development environment values
global:
  connect:
    restUrl: "http://kafka-connect-dev:8083"
    timeout: 300
    pollInterval: 5

# Kafka Connect cluster configuration
replicaCount: 1

kafka:
  bootstrapServers: "kafka-dev:9092"

deployment:
  replicas: 1
  heap:
    initial: 384m
    max: 768m
  resources:
    requests:
      cpu: 200m
      memory: 768Mi
    limits:
      cpu: 500m
      memory: 1Gi

# Connectors subchart configuration
connectors:
  enabled: true
  reconcile:
    enabled: true
    prune: false
  legacy:
    reconcileEnabled: false
  reconcileJob:
    heap:
      initial: 128m
      max: 256m
    env:
      - name: CONNECT_REST_URL
        value: "http://kafka-connect-dev:8083"
    resources:
      requests:
        cpu: 50m
        memory: 128Mi
      limits:
        cpu: 100m
        memory: 256Mi
  connectors:
    environment: "dev"
    mainConfigFile: "environments/dev/connectors.yaml"