# Test values for local Helm install with connectors
deployment:
  replicas: 1
  heap:
    initial: 384m
    max: 768m
  resources:
    requests:
      cpu: 200m
      memory: 768Mi
    limits:
      cpu: 500m
      memory: 1Gi

reconcileJob:
  enabled: true
  image:
    repository: python
    tag: "3.11-slim"
    pullPolicy: IfNotPresent
  heap:
    initial: 256m
    max: 384m
  env:
    - name: CONNECT_REST_URL
      value: http://kafka-connect:8083
    - name: CONNECT_REST_TIMEOUT_SECONDS
      value: "120"
    - name: CONNECT_REST_POLL_INTERVAL_SECONDS
      value: "5"

# Embed connectors directly for testing
connectors:
  mainConfig: |
    connectors:
      - name: mock-source-test
        config:
          connector.class: org.apache.kafka.connect.tools.MockSourceConnector
          tasks.max: 1
          topic: connect-test
      
      - name: verifiable-source-test
        config:
          connector.class: org.apache.kafka.connect.tools.VerifiableSourceConnector
          tasks.max: 1
          topic: verifiable-test
  
  backupConfig: |
    {
      "name": "backup-jdbc-source",
      "config": {
        "connector.class": "io.confluent.connect.jdbc.JdbcSourceConnector",
        "tasks.max": "2",
        "poll.interval.ms": "45000",
        "connection.url": "jdbc:postgresql://postgres:5432/backup",
        "connection.user": "connect",
        "connection.password": "backup-secret",
        "mode": "incrementing",
        "incrementing.column.name": "id",
        "topic.prefix": "backup-"
      }
    }