deployment:
  replicas: 1
  heap:
    initial: 384m
    max: 768m
  resources:
    requests:
      cpu: 200m
      memory: 768Mi
    limits:
      cpu: 500m
      memory: 1Gi

reconcileJob:
  enabled: true
  heap:
    initial: 256m
    max: 384m
  env:
    - name: CONNECT_REST_URL
      value: http://kafka-connect-dev:8083

connectors:
  mainConfig: |
    connectors:
      - name: file-source-test
        config:
          connector.class: org.apache.kafka.connect.file.FileStreamSourceConnector
          tasks.max: 1
          file: /tmp/test.txt
          topic: connect-test