# Default values for kafka-connect
replicaCount: 1

image:
  repository: confluentinc/cp-kafka-connect
  pullPolicy: IfNotPresent
  tag: "7.5.0"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 8083

# Kafka Connect configuration
connect:
  groupId: "connect-cluster"
  configStorageTopic: "connect-configs"
  offsetStorageTopic: "connect-offsets"
  statusStorageTopic: "connect-status"
  keyConverter: "org.apache.kafka.connect.storage.StringConverter"
  valueConverter: "org.apache.kafka.connect.storage.StringConverter"
  pluginPath: "/usr/share/java,/usr/share/confluent-hub-components"
  extraEnv:
    - name: CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR
      value: "1"
    - name: CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR
      value: "1"
    - name: CONNECT_STATUS_STORAGE_REPLICATION_FACTOR
      value: "1"

# Kafka cluster configuration - pointing to external cluster
kafka:
  bootstrapServers: "external-kafka:9092"

# Health checks
livenessProbe:
  httpGet:
    path: /
    port: http
  initialDelaySeconds: 30
  periodSeconds: 10

readinessProbe:
  httpGet:
    path: /connectors
    port: http
  initialDelaySeconds: 10
  periodSeconds: 5

resources:
  requests:
    cpu: 200m
    memory: 768Mi
  limits:
    cpu: 500m
    memory: 1Gi

volumeMounts: []
volumes: []

nodeSelector: {}
tolerations: []
affinity: {}

# Reconciliation job configuration
reconcileJob:
  enabled: true
  image:
    repository: python
    tag: "3.11-slim"
    pullPolicy: IfNotPresent
  heap:
    initial: 256m
    max: 384m
  env:
    - name: CONNECT_REST_URL
      value: http://kafka-connect-local-kafka-connect:8083

# Connector configurations
connectors:
  mainConfig: |
    connectors:
      - name: file-source-test
        config:
          connector.class: org.apache.kafka.connect.file.FileStreamSourceConnector
          tasks.max: 1
          file: /tmp/test.txt
          topic: connect-test
      - name: mock-source-test
        config:
          connector.class: org.apache.kafka.connect.tools.MockSourceConnector
          tasks.max: 1
          topic: mock-test-topic